package fr.jha.libraryapp.backend.models;

public enum Categories {
    FICTION,
    NON_FICTION,
    NOVEL,
    ROMANCE,
    SELF_HELP_BOOKS,
    CHILDREN_BOOKS,
    BIOGRAPHY,
    AUTOBIOGRAPHY,
    TEXT_BOOKS,
    POLITICAL_BOOKS,
    ACADEMIC_BOOKS,
    MYSTERY,
    THRILLER,
    POETRY_BOOKS,
    SPIRITUAL_BOOKS,
    COOK_BOOKS,
    ART_BOOKS,
    YOUNG_ADULT_BOOKS,
    BOARD_BOOKS,
    HISTORY_BOOKS
}
